name: Test

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: android

      - name: Download LFS
        run: |
          git lfs install
          git lfs pull

      - name: Extract imagefs.txz
        run: |
          echo "===Head entries:"
          tar -tf app/src/main/assets/imagefs.txz | head
          mkdir imagefs
          tar -xf app/src/main/assets/imagefs.txz -C imagefs

      - name: Remove 64 of imagefs
        run: |
          rm -rf \
          imagefs/opt/wine/lib/wine/x86_64-windows \
          imagefs/opt/wine/lib/wine/x86_64-unix \
          imagefs/usr/lib/aarch64-linux-gnu \
          imagefs/usr/lib/x86_64-linux-gnu \
          imagefs/opt/wine/bin/wine64 \
          imagefs/opt/wine/bin/wine64-preloader

      - name: Zip imagefs
        run: |
          cd imagefs
          tar -cJf ../imagefs.txz .
          cd ..
          echo "==Size of imagefs.txz:"
          du -sh imagefs.txz

      - name: List 64 of ubuntu-prepared.txz
        if: false
        run: |
          tar -tf obb_image_generator/ubuntu-prepared.txz | grep -i 64

      - name: List 64 of patches.txz
        if: false
        run: |
          tar -tf obb_image_generator/patches.txz | grep -i 64

      - name: List 64 of wine.txz
        if: false
        run: |
          tar -tf obb_image_generator/wine.txz | grep -i 64

      - name: Commit
        if: false
        run: |
          git config user.name "DarkCode2317"
          git config user.email "darkcode2317@gmail.com"

          git add .
          git commit -m "Test"
          git push origin android --force
      