name: Modify Repo

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  modify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: android

      - name: Preview imagefs
        run: |
          tar -tf app/src/main/assets/imagefs.txz | head -n 50
      